version: '2'
services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    networks:
      default: {}
      sf_monitoring:
        aliases: [fluentd]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

networks:
  sf_monitoring:
    external: true
